### ISSUE TITLE
Dashboard widget missing data

### ISSUE THREAD

**Issue by hossko** [tailwarden/komiser#642] opened 2023-03-20 11:48 UTC
**Describe the bug**
The dashboard grouping widget does not show any data from AWS account, even though the resources show in the inventory page

**To Reproduce**
1. After adding the AWS account, the grouping dashboard is not showing data.

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/34215790/226330676-04cf3507-9b0d-43c6-8e78-574ebe004656.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Please, add here more information about the context of the bug. For example:
Images and/or videos showing the bug:

- The link where the bug happened.
- The cloud provider you were interacting with.
- The email of the account you were using.
- The browser/device you were using.

**Comment by ShubhamPalriwala** [comment] 2023-06-14 09:34
Hey @hossko, I tried to reproduce the bug with the provided information but I wasn't able to, I can see the intended resources in my inventory as well as the dashboard with no error logs. Could you please pull the latest code and see if this still persists?
![image](https://github.com/tailwarden/komiser/assets/55556994/9d82d73a-7847-499e-b74e-5ab080a59244)

**Comment by ShubhamPalriwala** [comment] 2023-07-07 17:23
seems that the bug is fixed in the newer releases! @hossko I'm closing this for now, if you face this again, please reopen it and we'd be glad to assist you through it 🙏🏼

**Closed by ShubhamPalriwala** 2023-07-07 17:23 UTC
Labels: bug, question
