### ISSUE TITLE
Support Linode Object storage

### ISSUE THREAD

**Issue by jakepage91** [tailwarden/komiser#819] opened 2023-05-25 12:03 UTC
**Describe the solution you'd like**
Collect Linode Object Storage
**Additional context**
To get an idea of how to implement the collector, take the [Compute Instances](https://github.com/tailwarden/komiser/blob/master/providers/linode/compute/instances.go) resource as inspiration.

**Comment by professorabhay** [comment] 2023-07-10 13:57
Hey @ShubhamPalriwala, I'm working on it. 
![Screenshot_2023-07-10-19-24-38-324_com.github.android.png](https://github.com/tailwarden/komiser/assets/76243309/00b2eaf9-ddcc-4a48-86ec-a2af3a263f33)

How can I access it from linode go library?? 
I tried some but it giving error that it's not exist.

**Comment by ShubhamPalriwala** [comment] 2023-07-10 18:58
Hey @professorabhay, I just did some hit-and-trial and I think we can use the `ListObjectStorageBuckets()` method.

However, I see that we have already implemented this under the buckets in the PR: https://github.com/tailwarden/komiser/pull/353 hence this can be duplicate of #330 

I'll wait for @jakepage91 to confirm and maybe we can close this for now! Apologies for this, but can you please pick up another issue that is of interest to you? Let me know if you need a hand on it 🙏🏼

**Comment by professorabhay** [comment] 2023-07-11 00:20
Yes @ShubhamPalriwala, It's little bit confusing for now. I just checked official linodego client API  
GitHub and found that there is 2 methods.
![Screenshot_2023-07-11-05-43-17-892_com.github.android.png](https://github.com/tailwarden/komiser/assets/76243309/bc900247-e13b-4d4d-a00f-7dc8fcb53ddb)

For object-buckets, there is an other file.
Let's @jakepage91 look into it, till then let me test it locally.

**Closed** 2023-07-18 18:43 UTC
Labels: enhancement, good first issue, feature, linode
